name: game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_forge2d: ^0.18.2+3
  flame_audio: ^2.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/blueberryBall.png
  - assets/audio/pop.mp3
